# Copyright (c) Meta Platforms, Inc. and affiliates.

"""
CUTracer Python SDK

This package provides tools for validating, parsing, and analyzing
CUDA trace data generated by CUTracer.
"""

from importlib.metadata import PackageNotFoundError, version
from typing import Any, TYPE_CHECKING

try:
    __version__ = version("cutracer")
except PackageNotFoundError:
    __version__ = "0+unknown"  # Development mode or not installed

if TYPE_CHECKING:
    from cutracer.validation import (
        compare_trace_formats,
        validate_json_trace,
        validate_text_trace,
    )

__all__ = [
    "__version__",
    "validate_json_trace",
    "validate_text_trace",
    "compare_trace_formats",
]


def __getattr__(name: str) -> Any:
    # Keep the established convenience imports without loading trace readers
    # and their dependencies when importing the standalone analysis core.
    if name in __all__ and name != "__version__":
        from cutracer import validation

        value = getattr(validation, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
